### ISSUE TITLE
Схема базы данных

### ISSUE THREAD

**Issue by LegaKh** [LegaKh/LuckyFind#5]
Create db scheme and add it to Wiki.

**Comment by MorganFujimaka** [comment]
Done. See the wiki page https://github.com/LegaKh/LuckyFind/wiki/DB-Scheme

**Comment by oksanka-blaze** [comment]
а что делает табличка ads?

**Comment by MorganFujimaka** [comment]
Таблица ads является родительской для таблиц docs, pets и license_plates и хранит общие поля для всех типов найденных вещей. Соответственно в dosc, pets и license_plates хранятся уникальные поля для даного типа найденных вещей.

**Comment by oksanka-blaze** [comment]
ага, тогда в pets и license_plates не нужно поле ads_id (там же связь has_one по записи в таблице ads мы можем определить связь)

**Comment by MorganFujimaka** [comment]
точно, ошибка закралась, с users удалил, а из тех 2 нет )

**Comment by MorganFujimaka** [comment]
все, поправил https://github.com/LegaKh/LuckyFind/wiki/DB-Scheme

**Comment by oksanka-blaze** [comment]
:dancers:

**Comment by MorganFujimaka** [comment]
:relaxed:
